### ISSUE TITLE
Crash when connecting to Netatalk 2.4

### ISSUE THREAD

**Issue by briankendall** [anti-matter/AppleShare-IP-Browser#2]
I have Netatalk 2.4 running on a Linux server that I installed some months ago. If I connect to it with AppleShare-IP-Browser I still get a crash, unfortunately.

Granted things seem to work properly with Netatalk 4, and with its release there's not really any reason to use Netatalk 2 any longer, at least none that I'm aware of. (Maybe there are some systems that don't have packages for Netatalk 4, or can't run it for some reason, but I'm speculating.)

I think it'd be perfectly fine if you didn't want to fix it, but just in case you do, here's a stdlog of the crash, on an SE/30 running System 7.1:
[StdLog.txt](https://github.com/user-attachments/files/19797869/StdLog.txt)

(Note: this stdlog was copied over the network using AppleShare-IP-Browser!)

**Comment by anti-matter** [comment]
I do not have a linux system handy to test this, and 2.4 is quite old. For now I can't look at it, but may take a look in the future, so I'll leave this issue open for now, at least until I can confirm it's not worth fixing.

**Comment by anti-matter** [comment]
@briankendall can you reproduce the crash again, and this time type "SC" in the debugger and send me the output?

**Comment by briankendall** [comment]
Here you go:
```
 Calling chain using A6 links
  A6 Frame   Caller
  top level 00F1FC70 'CODE 0001 09EC E_MacTCP'+000F4
  011166C6  00F2A654 main+00050
  011166BA  00F2D470 CApplication_Run+00050
  01116670  00F2D55C CApplication_Process1Event+00058
  0111665C  00F4457A CSwitchboard_ProcessEvent+000B2
  01116636  0110FDDA LExtendoSwitchboard_DoIdle+0000C
  01116626  00F444A8 CSwitchboard_DoIdle+00022
  01116616  00F2DCD8 CApplication_Idle+0011A
  011165DE  00F25766 CBrowserDLOG_Dawdle+0004C
  01116120  00F311D8 'CODE 000A 09EC TCL5'+05408
  01115C16  01107F16 HandleFailure0+00048
```

**Comment by anti-matter** [comment]
@briankendall can you connect to the 2.4 server by using the Chooser and entering an IP address (instead of using AppleTalk)?

**Comment by anti-matter** [comment]
[AppleShareBrowserDBG.zip](https://github.com/user-attachments/files/19810117/AppleShareBrowserDBG.zip)

I think I fixed the crash which was actually in an error path. I attached a debug build here, please run this and try to login again. You'll likely get an error message this time with what the error is. This build has a debug output window, when you quit the app, please save the debug output and attach to this ticket.

Oh, rename the file attached from *.zip to *.sit.hqx (github wouldn't let me include it without changing the extension).

Thanks!!

**Comment by anti-matter** [comment]
I uploaded new release that fixes error paths and reports correctly when a supported UAM cannot be found on the server. Please try this and let me know if it solves the issue. My guess is that you need to enable ClearTxt passwrd to get fix this error on 2.4.x.

**Comment by briankendall** [comment]
I do indeed get an error when trying to connect now. However, the app still crashes after I dismiss the error window. 😞 Let me know if you'd like another log or stack crawl.

**Comment by anti-matter** [comment]
@briankendall and this is using the debug build from the other ticket? Or, the new release I posted yesterday (which has a couple extra fixes in it as well)? If so, try to grab the output of the debug window (may need to take a pic) and yes, please do an SC in the debugger.

**Comment by briankendall** [comment]
Here's a stack crawl + stdlog:
[log2.txt](https://github.com/user-attachments/files/19825628/log2.txt)

**Comment by anti-matter** [comment]
@briankendall Thanks, but what was the debug output from the debug build I posted?

**Comment by briankendall** [comment]
Oh right, sorry, I forgot to say. This is the release you put up yesterday, 1.0b27.

edit: Oops, no idea how I managed to close the ticket.

**Comment by anti-matter** [comment]
Edit: removed download, use file in next comment below.

Please rename above file to have a .hqx extension, expand, and reproduce with app inside. Be sure to have the Debug Output window visible so you can grab a pic of it after the crash happens (press the escape key in the debugger to get back to desktop view).

The netatalk server is sending something back unexpected that is causing the crash and the debug output should show us what that is.

Also, what is the error you are getting before it crashes?

Thanks!

**Comment by anti-matter** [comment]
[AppleShareBrowser.zip](https://github.com/user-attachments/files/19825760/AppleShareBrowser.zip)

Here is an update to the debug build with a fix for the crash you were seeing. So now you should be able to just save the debug output to a file and upload it here.

**Comment by briankendall** [comment]
Here you go:

[Debug Output.txt](https://github.com/user-attachments/files/19829282/Debug.Output.txt)

**Comment by anti-matter** [comment]
Ok, glad to see the crash(es) are fixed now. You should be receiving an error message that says, `The server does not support a UAM compatible with this client.` The simple fix here is to enable the `ClearTxt Passwrd` UAM on the server side.

Thanks for working through all the crashes with me, this was a big help!

**Comment by briankendall** [comment]
No problem, this is a great tool! I can connect to AFP shares over IP in System 7.1 now, since it lacks the version of AppleShare that can connect to IP addresses directly. And it works faster than FTP.

I don't know what features you're interested in with this app, but I'll just toss this out there: adding some AppleScript support so that it can automate downloading and uploading files would be superb.
